# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Swaroop Narasimha
tagline:          'Random interests, coding and learning'
url:              http://www.swaroop.co.in
shorturl:         swaroop.co.in

author:
  name:           'Swaroop Narasimha'
  url:            http://swaroopgn.tumblr.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/swaroopgn/swaroopgn.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
