# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Swaroop Narasimha
tagline:          'Random interests, coding and learning'
url:              http://www.swaroop.co.in
shorturl:         swaroop.co.in

author:
  name:           'Swaroop Narasimha'
  url:            http://swaroopgn.tumblr.com

paginate:         5
baseurl:             /

# Custom vars
version:          1.0.0

github:
  repo:           github.com/swaroopgn/swaroopgn.github.io

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
